- .github/auto_assign.yml
- .github/workflows/auto_assign.yml
- close #13 
1. PR 리뷰어 자동 할당되도록 설정하였습니다. 
2. assignees 는 작성자로 자동 배정되도록 설정했습니다!
작동 잘 되는지는 머지가 되어야 확인할 수 있을 것 같아요.. 
작동 안되면 잘 수정해서 다시 올려둘게요
> [init] 오토 리뷰어 깃헙 액션 추가

- public/svgs/ic_right.svg
- src/asset/svg/IcRight.tsx
- src/asset/svg/index.ts
- src/common/component/TextField/index.tsx
- src/page/community/component/Tag/Tag.css.ts
- src/page/community/component/Tag/Tag.tsx
- src/page/community/write/Write.tsx
- close #76
Tag 컴포넌트는 계속 활성화 되어야 하는 특징이 있어서
상태를 꼭 갖고 있어야 할 것 같더라구요.
그래서 선택에 따른 set 함수도 props 로 받게 되어 있습니다.
> [feat/#76] Tag 컴포넌트

- src/common/component/HeaderNav/HeaderNav.css.ts
- close #98 
- 구현영상
https://github.com/user-attachments/assets/b72f343e-324c-426b-941e-99aab90bd496
> [fix] 헤더 네브 사이즈 수정

- .github/workflows/forkMain.yml
- close #11 
develop, main fork 액션 yml 작성
바로 머지하겠습니다.
> [Feat/#11] 버셀 배포 (fork 액션 추가)

- .github/workflows/forkDevelop.yml
- .github/workflows/forkMain.yml
> fix: 로컬 액션 조건문 추가

- src/api/domain/registerPet/petId/hook.ts
- src/api/domain/registerPet/petId/index.ts
- src/page/registerPet/index/RegisterPet.tsx
- src/page/registerPet/index/common/dropDown/constant.ts
- src/page/registerPet/index/component/petId/PetId.tsx
- close #131 
api 연동할 수 있는 구조 만들고 품종조회 api 연결했습니다. 
깜빡임은 api 연동 다하고 추후 잡겠습니다.
- 구현화면 (고양이 조회 -> 강아지 조회)
https://github.com/user-attachments/assets/f99853a7-ec66-4798-ac59-c2634b5c9d78
> [Feat/#131] 품종 조회 api 연동

- src/api/domain/mypage/edit-pet/hook.ts
- src/api/domain/mypage/edit-pet/index.ts
- src/api/domain/mypage/hook.ts
- src/api/domain/mypage/index.ts
- src/api/index.ts
- src/page/mypage/edit-pet/PetEdit.css.ts
- src/page/mypage/edit-pet/PetEdit.tsx
- src/page/mypage/index/Mypage.tsx
- src/page/mypage/index/component/MyPageComment/MyPageComment.tsx
- src/page/mypage/index/component/MyPageContent/MyPageContent.css.ts
- src/page/mypage/index/component/MyPageContent/MyPageContent.tsx
- src/page/profile/index/Profile.css.ts
- src/page/profile/index/Profile.tsx
- src/page/profile/index/component/ProfileComment/ProfileComment.css.ts
- src/page/profile/index/component/ProfileComment/ProfileComment.tsx
- src/page/profile/index/component/ProfileContent/ProfileContent.css.ts
- src/page/profile/index/component/ProfileContent/ProfileContent.tsx
- src/page/setting/edit-profile/ProfileEdit.css.ts
- src/page/setting/edit-profile/ProfileEdit.tsx
- src/page/setting/index/Setting.css.ts
- src/shared/util/renderAllComents.ts
- src/type/schema.d.ts
- close #136 
최대 7개의 칩만 선택할 수 있게 만들고, 클릭했을 때 스타일 변하는 것을 방지하기 위해 현재 클릭된 것이 7개 미만인지,
7개 이상이더라도 해당 id를 가진 칩은 토글이 가능하도록 구현했습니다.
나머지 구현 내용은 api 연결, 반응형 구현, 파일 위치 수정입니다.
프로필페이지
마이페이지
> [Feat/#136] 마이페이지 & 프로필페이지 API 연결

- src/common/component/Nav/Nav.css.ts
- src/page/community/category/Category.tsx
- src/page/main/index/Main.tsx
> [Bug/#168] 디자인 미반영 사항, 카테고리별 게시글 조회 api 수정

- src/api/domain/community/search/index.ts
- src/api/domain/setting/hook.ts
- src/api/domain/setting/index.ts
- src/common/component/BottomSheet/BottomSheet.css.ts
- src/page/setting/index/Setting.tsx
> [Feat/#174] 로그아웃 및 사파리 브라우저 주소창 가림 이슈 해결

- index.html
- src/page/mypage/edit-pet/component/CategoryBottomSheet/CategoryBottomSheet.tsx
- src/page/mypage/edit-pet/component/CategoryBottomSheet/components/DropDownText/DropDownText.tsx
- src/page/mypage/index/Mypage.css.ts
- src/page/mypage/index/Mypage.tsx
- src/page/mypage/index/component/MyPageContent/MyPageContent.css.ts
- src/page/mypage/index/component/MyPageContent/MyPageContent.tsx
- src/page/profile/index/Profile.css.ts
- src/page/profile/index/Profile.tsx
- src/page/profile/index/component/ProfileContent/ProfileContent.css.ts
- src/page/profile/index/component/ProfileContent/ProfileContent.tsx
> [Feat/#180] 마이페이지, 프로필 페이지 qa

- package.json
- pnpm-lock.yaml
- src/common/component/Loading/Loading.css.ts
- src/common/component/Loading/Loading.tsx
- src/page/onboarding/complete/Complete.tsx
- src/page/register-pet/complete/Complete.tsx
> [Fix/#199] 로티 라이브러리 변경 

- src/common/component/Comment/Comment.tsx
- src/common/component/SubComment/SubComment.tsx
> fix: 댓글 프로필 클릭시에도 이동하도록 구현

- src/common/component/Divider/Divider.css.ts
- src/common/component/Divider/Divider.tsx
- src/page/community/category/Category.css.ts
- src/page/main/index/hotPost/HotPost.css.ts
- src/page/main/index/hotPost/HotPost.tsx
- src/page/main/index/symptomDetail/SymptomDetail.css.ts
- src/page/main/index/symptomDetail/SymptomDetail.tsx
- close #196 
https://github.com/user-attachments/assets/f1d0870f-3d34-4a81-aeab-60b0b679f899
> [Feat/#196] 메인 qa2 차

- src/page/main/index/symptomDetail/SymptomDetail.css.ts
> [feat/ #205] 헤더부분 수정

- src/page/community/[postId]/PostDetail.css.ts
- src/page/main/index/symptomDetail/SymptomDetail.css.ts
- src/page/main/index/symptomDetail/SymptomDetail.tsx
> [Feat / #207 ] 게시물 상세 댓글 마진 수정/ 검색결과 없음 페이지 스타일 수정

- src/page/community/index/components/SelectPost/SelectPost.css.ts
- src/page/community/index/components/SelectPost/SelectPost.tsx
- src/page/main/index/symptomDetail/SymptomDetail.css.ts
> [feat/#211 ] 게시글 없을 때 페이지 추가

- src/page/register-pet/index/common/ProgressBar/ProgressBar.css.ts
> [design] 프로그래스바 변경

- src/page/community/[postId]/PostDetail.tsx
- src/page/community/category/Category.tsx
> [feat/#216] 속성 수정

- src/page/community/[postId]/PostDetail.css.ts
> [Feat/#218] width 값 수정

- src/page/community/index/components/SelectPost/SelectPost.tsx
- src/page/main/index/Main.tsx
- src/page/main/index/hotPost/HotPost.css.ts
- src/page/main/index/hotPost/HotPost.tsx
- src/page/main/index/symptom/Symptom.tsx
> [Feat/#221] 

- src/api/domain/mypage/hook.ts
- src/api/domain/mypage/index.ts
- src/page/community/[postId]/PostDetail.css.ts
- src/page/community/[postId]/PostDetail.tsx
- src/page/community/utills/getFillterNamebyid.ts
- src/page/community/write/Write.tsx
- src/page/login/Login.tsx
- src/page/main/index/Main.tsx
- src/route/useProtectedRoute.tsx
> [Bug/#223] redirecting 및 개행 처리

- src/api/domain/community/post/hook.ts
- src/asset/svg/IcDelete.tsx
- src/common/component/BottomSheet/BottomSheet.tsx
- src/common/component/Chip/Chip.tsx
- src/common/component/Comment/Comment.tsx
- src/common/component/SubComment/SubComment.tsx
- src/common/component/Toast/Toast.tsx
- src/common/component/WornningToastWrap/WorningToastWrap.css.ts
- src/common/component/WornningToastWrap/WorningToastWrap.tsx
- src/page/community/[postId]/PostDetail.tsx
- src/page/community/category/Category.tsx
- src/page/community/search/index/Search.css.ts
- src/page/community/search/index/Search.tsx
- src/page/community/write/Write.tsx
- src/page/register-pet/index/component/petHealth/PetHealth.tsx
- src/shared/component/FilterBottomSheet/FilterBottomSheet.tsx
- src/type/global.d.ts
- src/type/schema.d.ts
> [Feat/#222] qa 4차

- src/common/component/Button/styles.css.ts
- src/page/register-pet/index/component/petName/PetName.tsx
> [Feat/#225]onboarding qa2 반영

- src/api/domain/community/search/index.ts
- src/page/main/index/symptomDetail/SymptomDetail.tsx
- close #229 
해당 포스트 누르면 해당 관련 글 리스트가 뜨지 않았는데 의진이와의 협동으로 bodyId 추가해서 해결함!!!!!!!!!!!!!
얏 호
> [feat/ #229 ]: 증상 필터링!!!!

- src/api/index.ts
- close #235 
윤지야 나중에 작업할 때 참고해 ~!
> [Fix] 401일 경우 토큰 삭제

- index.html
> [ test ] 사용성 테스트(maze) 연동을 위한 코드 추가

- src/api/domain/onboarding/nickname/hook.ts
- src/api/domain/onboarding/nickname/index.ts
- close #269 
닉네임 patch
원래는 파라미터로 보냈는데, 리퀘스트 바디로 변경됐다고 하셔서 맞게 변경했습니다! 
https://github.com/user-attachments/assets/a625cbf5-77b3-439f-992e-15d56d5334a1
> [Feat/#269] 닉네임 api 변경사항 반영

- package.json
- pnpm-lock.yaml
- public/svgs/ic_chevronRight2.svg
- src/app/register-pet/index/common/dropDown/DropDown.css.ts
- src/app/register-pet/index/common/dropDown/DropDown.tsx
- src/app/review/write/_component/DirectMyPetInfo.style.css.ts
- src/app/review/write/_component/DirectMyPetInfo.tsx
- src/app/review/write/_component/ReviewDate.style.css.ts
- src/app/review/write/_component/ReviewDate.tsx
- src/app/review/write/_component/ReviewHospital.style.css.ts
- src/app/review/write/_component/ReviewHospital.tsx
- src/app/review/write/_component/ReviewPetInfo.style.css.ts
- src/app/review/write/_component/ReviewPetInfo.tsx
- src/app/review/write/page.tsx
- src/app/review/write/styles.css.ts
- src/asset/svg/IcChevronRight2.tsx
- src/asset/svg/index.ts
- src/common/component/Button/index.tsx
- src/common/component/Radio/Radio.css.ts
- src/common/component/Radio/Radio.tsx
- src/common/component/TextField/index.tsx
- src/common/component/TextField/styles.css.ts
- src/shared/component/SearchHospital/Card.css.ts
- src/shared/component/SearchHospital/Card.tsx
- src/shared/component/SearchHospital/SearchHospital.css.ts
- src/shared/component/SearchHospital/SearchHospital.tsx
- src/shared/hook/useDebounce.ts
Reverts cocos-pet/cocos-frontend#273
리버트에 리버트 조지기~
> Revert "Revert "[Feat/#255] 병원리뷰 (1/4)뷰 ""

- src/api/constants/apiPath.ts
- src/api/shared/hook.ts
- src/api/shared/index.ts
- src/app/mypage/_component/AddFavoriteHospital.tsx
- src/shared/component/SearchHospital/Card.tsx
- src/shared/component/SearchHospital/SearchHospital.css.ts
- src/shared/component/SearchHospital/SearchHospital.tsx
- src/type/schema.d.ts
- close #294 
https://github.com/user-attachments/assets/483501bd-95cb-4bea-ae4a-ad87f09b74e8
병원 이름이 생각보다 길어서 UI가 깨지는 경우가 존재하는데... 
이건 나중에 디자이너 선생님들 QA를 받고 수정하거나, 아니면 문의 드려서 대응해야할 것 같아요~!
> [Feat/#294] 병원 검색 바텀 시트 API 연결 및 무한 스크롤 구현

- src/app/mypage/edit-pet/PetEdit.css.ts
- src/app/mypage/edit-pet/page.tsx
- close #253 
우선 중복되는 UI 코드가 있길래 그 부분 간단하게 리팩토링하고,
병원 수정 바텀시트 연결했어요. (+ 뷰도 추가)
https://github.com/user-attachments/assets/11f02f2b-a8d9-47b4-87ae-651fa5c8b0ac
> [Feat/#253] 반려동물 수정 페이지 추가 구현

- src/app/mypage/_component/AddFavoriteHospital.tsx
- src/app/mypage/_style/mypage.css.ts
- src/app/profile/_component/ProfileSection/FavoriteHospital.css.ts
- src/app/profile/_component/ProfileSection/ProfileSection.tsx
- src/type/schema.d.ts
- close #301 
방문 목적이 response 추가되면서, 코드젠하는 간단한 작업이에요~
간단하게 디자인 수정된 거 있어서 같이 반영해요.
> [Feat/#301] 방문 목적 response 추가 (Simple)

- src/app/review/complete/page.tsx
- src/app/review/complete/style.css.ts
- close #266 
리뷰 등록 완료(review/complete) 뷰 퍼블리싱 완료 했습니다.
확인하기 버튼의 경우 아직 확정받지 못해서 main으로 이동하게 임시 처리해두었고, 
추후 확정나면 `path`활용해서 수정하겠습니다. 
-  확인하기 버튼 사이즈를 고정했습니다!
확인하기 사이즈가 '리뷰가 등록되었어요' 타이틀 `width`사이즈와 동일하길래, 이를 의도하신거 같아 다른 뷰와 달리 width값을 고정했습니다.
https://github.com/user-attachments/assets/eed03ea1-3263-4fe5-8335-d692f1af092d
> [Feat/#266] 리뷰 등록 완료 뷰 퍼블리싱

- src/app/mypage/_component/AddFavoriteHospital.tsx
- src/app/mypage/_style/mypage.css.ts
- src/app/profile/_component/ProfileSection/FavoriteHospital.css.ts
- src/app/profile/_component/ProfileSection/ProfileSection.tsx
- src/type/schema.d.ts
https://github.com/cocos-pet/cocos-frontend/pull/302 를 재적용해요.
> 방문 목적 response 추가 재적용

- src/app/community/[postId]/page.tsx
- src/app/community/index/Community.tsx
- src/app/community/write/Write.tsx
- src/app/community/write/page.tsx
- src/app/login/Login.tsx
- src/app/login/page.tsx
- src/app/main/page.tsx
- src/app/mypage/page.tsx
- src/app/profile/page.tsx
- src/app/setting/edit-profile/ProfileEdit.tsx
- src/app/setting/index/Setting.tsx
- src/app/setting/page.tsx
> [Feat][#333] useProtectedRoute 적용 필요 없는 곳에서 제거

- src/app/setting/page.tsx
> [Bug][#347] 빌드테스트 실패 원인 해결

- .gitignore
- src/app/main/_section/hotPost/HotPost.tsx
- src/app/main/_section/symptom/Symptom.tsx
- src/app/main/page.tsx
- src/common/component/Loading/Loading.tsx
- src/shared/component/If/if.tsx
- src/shared/component/NoData/NoData.tsx
- close #351
**1. main 오류 fix** 
main 페이지에 데이터가 안 뜨면 아예 null 처리를 해두어서 문제가 있었어요. 
그 부분을 모두 날리고, 
컴포넌트 내부에서 데이터가 없을 때 ui 를 띄우도록 구현했습니다. 
동시에 분기처리가 많아져서 IF 컴포넌트를 만들었어요! 
2. If component 
다음과 같이 사용하시면 됩니다. 
```
<If condition={isLoading}>
<Loading height={20} />
</If>
```
3. 메뉴 데이터 안 뜨면 그냥 안 보이도록 처리 
지금 서버 이슈로 데이터 안 뜨니까 그냥 메뉴가 접근이 안 되더라구요 
그래서 데이터가 없을 때 메뉴가 우선 안 보여지도록 했습니다. 
-> 최선을 다해 메뉴 데이터가 안 뜰 경우를 없애야겠죠 그래선 안되니까.. 
as is 
tobe 
https://github.com/user-attachments/assets/5cebc2a4-ac7e-44cf-9cb5-a30759e5564b
> [Feat/#351] main page hotfix , if component 

- public/svgs/ic_rightArrow.svg
- src/app/community/detail/SymptomDetail.css.ts
- src/app/community/detail/_section/HospitalReviewFilter.tsx
- src/app/community/detail/_section/ReviewDetailContent.tsx
- src/app/community/detail/page.tsx
- src/asset/svg/IcRightArrow.tsx
- src/asset/svg/index.ts
- src/common/component/Button/styles.css.ts
- src/common/component/Modal/Modal.tsx
- close #344 
토큰 없을 때 비로그인 로직 구현했습니다 
또한 비로그인 시 필터 기능 없애기 위해 아예 삭제한 점 참고해주세요
https://github.com/user-attachments/assets/c39f7729-1334-4ee2-95f0-1a44c007ae76
> [Feat/#344] 메인 - 부위별 병원 리뷰 비로그인 로직 

- src/app/not-found.tsx
404 페이지의 타이머가 동적으로 변해, 곧 이동할 것임을 유저에게 알려요
간단한 작업이라 바로 머지해둘게요!
> [Feat] 타이머 시간 변하는 기능 추가

- src/app/hospital-detail/[hospitalId]/_component/InfoContent/InfoContent.tsx
- src/app/hospital-detail/[hospitalId]/_component/KakaoMap/KakaoMap.tsx
- src/app/hospital-detail/[hospitalId]/_component/MapComponent/MapComponent.css.ts
- src/app/hospital-detail/[hospitalId]/_component/MapComponent/MapComponent.tsx
- close #387 
.env 파일에 넣을 키는 채널톡에 게시하겠습니다!
> [QA] [fix: 지도 이미지 안 뜨는 문제 해결]

- src/api/domain/community/detail/hook.ts
- src/api/domain/community/detail/index.ts
- src/app/hospital-detail/[hospitalId]/_component/ReviewContent/RecentView/RecentView.tsx
- src/app/hospital-detail/[hospitalId]/more-reviews/MoreReview/MoreReview.css.ts
- src/app/hospital-detail/[hospitalId]/more-reviews/MoreReview/MoreReview.tsx
- src/app/hospital-detail/[hospitalId]/more-reviews/page.tsx
- close #392
https://github.com/user-attachments/assets/7ea18fbb-d0c7-4fc8-99c3-d23f9591f15b
> [feat/#392] review qa

- src/api/domain/community/detail/hook.ts
- src/api/domain/community/detail/index.ts
- src/app/hospital-detail/[hospitalId]/_component/ReviewContent/RecentView/RecentView.tsx
- src/app/hospital-detail/[hospitalId]/more-reviews/MoreReview/MoreReview.tsx
- src/app/review/page.tsx
- src/shared/component/ReviewItem/ReviewItem.tsx
- close #394 
무슨 이유인지 모르겠는데... 현재 develop에 있는 HospitalReview 컴포넌트가 저랑 다르더라구요.
(git pull 하면 everything-up-to-date nnn번째 반복...)
해당 컴포넌트 누락 이슈 해결하고 방문목적 추가 했습니다.
> [Feat/#394] 방문목적 추가

- src/app/setting/withdraw/page.css.ts
> [QA][#398] 회원 탈퇴 페이지 반응형 구현

- src/auth/RedirectKakao.tsx
> fix: 라우팅 방식 변경

- src/app/hospital-detail/[hospitalId]/_component/InfoContent/InfoContent.tsx
> [Feat/#417] 병원 태그 없을 때

- .env.example
- src/app/community/write/page.tsx
- src/app/mypage/edit-pet/page.tsx
> Init and notice

- src/api/index.ts
- src/app/auth/page.tsx
- close #428 
dev에서도 로그인이 안되는게 이상해서 디버깅해봤어요.
확인 결과 url이 이상한걸 발견했고, 수정된 api url을 제대로 반영해두지 않은 것을 확인했어요. 
따라서 수정해요.
> [Fix][#428] dev 로그인 안되는 이슈 해결

- .env.example
- .github/workflows/forkDev.yml
- src/api/index.ts
- src/app/review/write/_component/ReviewDate.tsx
> 로그인 이슈 main에도 반영

- src/app/hospital-detail/[hospitalId]/_component/InfoContent/InfoContent.tsx
- src/app/hospital-detail/[hospitalId]/_component/KakaoMap/KakaoMap.tsx
- src/app/hospital-detail/[hospitalId]/_component/MapComponent/MapComponent.tsx
- close #439 
현재 카카오맵을 그릴 때 주소로 검색하고 있는데, 정확성 문제로인해 서버에 위,경도 추가 요청을 하고 타입을 추가했습니다.
그에 기반하여 지도를 그립니다.
기존에 지도에 그려지지 않던 병원들이 그려집니다.
> [Refactor/#439] 카카오맵 리팩토링

- package.json
- pnpm-lock.yaml
- src/app/Provider.tsx
- src/app/layout.tsx
> [Feat/#466] GTM 연결

- src/app/community/[postId]/PostDetail.css.ts
- src/app/community/[postId]/page.tsx
- src/common/component/TextField/index.tsx
- src/style/global.css.ts
- close #474
핸드폰 테스트가 어려워서 다시 수정해서 올립니다. 
이전 PR 에서 수정한 내용으로는 해결이 안 돼서 다른 해결 방법을 한번 머지해볼게요..!
> [Fix/#474] Input 집나가는 문제 해결
