biome.json, package.json, pnpm-lock.yaml, src/common/component/Divider/Divider.css.ts, src/common/component/Divider/Divider.tsx, src/common/component/Spacing/Spacing.css.ts, src/common/component/Spacing/Spacing.tsx, src/page/main/index/Main.tsx
- close #21 
- 바닐라 익스트랙트에서 동적 변수를 통한 스타일링을 위해서는 createVar() 뿐만 아니라 assignInlineVars 를 사용해야하기 때문에 @vanilla-extract/dynamic 를 추가로 설치했습니다. 
- 바닐라 익스트랙트의 스타일링을 위해서는 반드시 .css.ts 파일로 분리하여 작성해야 합니다. (rule)
- 동적 변수 스타일링이 아닌 다양한 variants를 적용하기 위해서는 recipe()을 사용했습니다. 이를 위해 @vanilla-extract/recipe를 설치했습니다.
- 간단히 말해, recipe는 정해진 스타일 변형을 위한 규격화된 방식, assignInlineVar는 컴포넌트가 렌더링될 때 동적으로 값이 할당하는 방식이라고 생각하시면 됩니다.
사용방법은 간단합니다.
위, 아래로 간격을 주고 싶을 때 <Spacing/> 을 사용하는데, marginBottom이라는 prop에 rem 단위의 값을 숫자(형식은 문자열)만 입력하면 됩니다. 위의 예시는 10rem의 간격을 주었습니다. (prop은 optional, default 값은 1(rem))
<Divider/>는 size 라는 prop에 "large" | "small" 중 하나를 주면 됩니다. (prop은 optional, default 값은 "large")
사용한 모습 (예시, main에 있는건 언제든 지워도 좋습니다.)
=> [Feat/#21] Spacing & Divider 컴포넌트 구현

src/common/component/BottomSheet/BottomSheet.tsx, src/page/community/[postId]/Post.ts, src/page/community/[postId]/Post.tsx, src/shared/component/MoreModal/MoreModal.css.ts, src/shared/component/MoreModal/MoreModal.tsx, src/shared/hook/useMoreModal.ts
- close #60 
게시물 삭제 모달 구현했습니다. 
해당 모달은 게시물을 삭제하거나, 댓글을 삭제하는 용도로 쓰일 예정입니다.
interaction 정의된 게 없어서, 디자이너께 button 클릭 시 디자인을 요청 드렸습니다.
만들어주신 해당 디자인에 대해 :active css 주었습니다.
... 버튼의 위치가 변경되어도 그 것에 맞게 따라다니도록 구현하였습니다! (영상 확인)
[ 해당 컴포넌트가 쓰이는 곳, 수정해야하는 곳 ]
1. 댓글 컴포넌트
2. 대댓글 컴포넌트
3. 헤더 컴포넌트
에 해당 컴포넌트로 변경 필요할 수 있을 것 같습니다. 
그리고 유저가 쓴 게시물인 경우에만 해당 버튼이 보여야 하기 때문에, 
헤더에서도 props 수정이 불가피해보입니다. 
댓글 컴포넌트도 마찬가지로 불가피해보입니다.
-> 추후 디테일 페이지 구현하면서 해당 내용 추가로 수정해두겠습니다!
[ 컴포넌트 @params ]
다음과 같이 아이콘 사이즈 변경 가능합니다. 
현재는 2.4rem, 2.0rem 두 가지 설정해두었습니다.
```
export const moreIcon = recipe({
base: {
width: "2.4rem",
height: "2.4rem",
},
variants: {
iconSize: {
"24": {
width: "2.4rem",
height: "2.4rem",
},
"20": {
width: "2.0rem",
height: "2.0rem",
},
},
},
});
```
[ 해당 컴포넌트 사용 방법 ]
이렇게 useMoreModal 훅을 만들었습니다.
위치는 …
=> [Feat/#60] 게시물 삭제 모달 구현

src/common/component/SimpleBottomSheet/SimpleBottomSheet.css.ts, src/common/component/SimpleBottomSheet/SimpleBottomSheet.tsx, src/page/test/Test.tsx, src/route/Router.tsx, src/shared/hook/useSimpleBottomSheet.ts
- close #90 
간단하니까 생략
사용 방법 - 이미지 참참고
1. SImpleBottomSheet import 해서 필요한 prop들 잘 넣어주기
2. useSimpleBottomSheet() 훅도 같이 받아와서 isOpen을 심플바텀시트 prop으로 넘겨줌
없음
=> [Refactor/#90] SimpleBottomSheet 리팩토링

package.json, src/api/constants/apiPath.ts, src/api/domain/community/post/hook.ts, src/api/domain/community/search/hook.ts, src/api/domain/community/search/index.ts, src/api/index.ts, src/page/community/search/index/Search.tsx, src/type/schema.d.ts
- close #106 
쿼리 키 세팅 했습니다.
```typescript
/**
* @description 최근 검색어 조회 API
*/
export const useSearchGet = () => {
return useQuery({
queryKey: SEARCH_QUERY_KEY.SEARCH_QUERY_KEY(),
queryFn: () => {
return getSearch();
},
});
};
```
다음과 같이 상수로 import 해서 사용하세요.
준혁오빠가 세팅한 거 보니까 쿼리키는 자기가 사용하는 쿼리키로 따로 만들어서 쓰더라구요!
저는 주로 아예 QUERY_KEY 를 하나의 객체로 그 안에 구성되도록 했었는데,
준혁 오빠 방법이 충돌도 적을 것 같아서 좋아 보입니다!
다들 어떻게 생각하는지 얘기해주시면 좋을 것 같아요
우선 제가 사용하는 SEARCH 는 파라미터가 없어서 
```typescript
export const SEARCH_QUERY_KEY = {
SEARCH_QUERY_KEY: () => ["search"],
};
```
다음과 같이 세팅해두었습니다.
이거 아직 서버 CORS 에러 해결해야해서 그거 확인하고 코리 달아주시면 좋을 것 같아요 
🚨 아직 아님 🚨
=> [feat/#106] 최근 검색어 GET api 연동 

src/api/domain/complete/hook.ts, src/api/domain/complete/index.ts, src/page/onboarding/complete/Complete.tsx, src/page/registerPet/complete/Complete.tsx
- close #142 
온보딩과 반려동물 등록 마지막에 나오는 닉네임 api 연동했습니다.
- 구현화면 (온보딩, 반려동물 등록)
=> [Feat/#142] 닉네임 조회 api 

src/api/domain/onboarding/nicknameDuplicate/hook.ts, src/api/domain/onboarding/nicknameDuplicate/index.ts, src/page/onboarding/index/component/nickname/Nickname.tsx, src/shared/util/validateNickname.ts
- close #145 
닉네임 중복조회 api 연동했습니다.
닉네임 중복 에러 메시지 반영을 위해 작성해 두었던 중복검사 로직 삭제하고 에러메시지 반환할 수 있도록 연결해두었습니다.
- 구현화면(현재 존재하는 닉네임명-> 키키)
https://github.com/user-attachments/assets/65bae180-7a71-4a15-a823-5c37e7027168
=> [Feat/#145] 닉네임 중복검사 api 연동

src/api/domain/community/post/hook.ts, src/api/domain/community/post/index.ts, src/common/component/Comment/Comment.tsx, src/common/component/Comment/CommentList.tsx, src/common/component/SimpleBottomSheet/SimpleBottomSheet.css.ts, src/common/component/SimpleBottomSheet/SimpleBottomSheet.tsx, src/common/component/SubComment/SubComment.css.ts, src/common/component/SubComment/SubComment.tsx, src/common/component/SubComment/SubCommentList.tsx, src/page/community/[postId]/Post.tsx, src/page/mypage/edit-pet/store/categoryFilter.ts, src/shared/util/formatTime.ts
- close #135
댓글 api, 대댓글 api 연동 두개 하면서
simple Bottom Sheet 에서 문제가 많이 생겼는데요,
subcomment 인지 comment 인지 확인하는 전역 상태 만들어서 
그 값을 받아 수행하도록 해결하였으며,
comment id 를 따라가지 못하는 문제를 props 로 받으면서 해결했습니다.
```typescript
interface SubCommentListProps {
subComments: commentGetRequestSubCommentType[];
onCommentDelete: (id: number) => void;
}
const SubCommentList = ({
subComments,
onCommentDelete,
}: SubCommentListProps) => {
```
```typescript
interface SubCommentProps {
subComment: commentGetRequestSubCommentType;
onReplyClick?: (id: number | undefined) => void;
onCommentDelete: () => void;
}
const SubComment = ({
subComment,
onReplyClick,
onCommentDelete,
}: SubCommentProps) => {
```
고민을 많이 했는데요, Comment delete 하는 함수를 Subcomment 로 보내서 
모든 delete 하는 로직을 Subcomment 함수 내에서 핸들링 하도록 구현 했습니다. …
=> [Feat/#135] 게시물 삭제 api , 댓글 삭제 api, 대댓글 삭제 api 연동

src/api/domain/register-pet/petId/hook.ts, src/page/onboarding/index/component/nickname/Nickname.tsx, src/page/register-pet/index/common/ProgressBar/ProgressBar.css.ts, src/page/register-pet/index/component/petHealth/disease/Step1.css.ts, src/page/register-pet/index/component/petHealth/disease/Step1.tsx, src/page/register-pet/index/component/petHealth/disease/Step2.css.ts, src/page/register-pet/index/component/petHealth/symptom/SymStep1.tsx, src/page/register-pet/index/component/petId/PetId.tsx, src/page/register-pet/index/component/petName/PetName.css.ts, src/page/register-pet/index/component/petName/PetName.tsx
- close #158 
레이아웃이 자잘하게 안맞는게 있어서 반영 완료했습니다.
반응형으로 해보니까 몇 개가 안맞더라고요.. 수정 완료했습니다.
드롭 다운 클릭 시 깜!빡 하는 문제가 있었습니다. 
리액트 쿼리의 옵션으로, 해당 옵션을 활용함으로써 새로운 쿼리키로 재패치하기 전까지 이전 값을 유지할 데이터를 만들어주는
`placeholderData: keepPreviousData,`
로 해결했습니다. 
- 스무스하게 드롭다운 내용 텍스트필드 반영
https://github.com/user-attachments/assets/868c9afe-4233-4237-befc-71ad7c878d5a
=> [Feat/#158] 온보딩 ~ 반려동물 등록 반응형 레이아웃 구현 및 데이터 요청 시 깜빡임 문제 해결

src/App.tsx, src/api/domain/mypage/index.ts, src/page/community/[postId]/PostDetail.tsx, src/page/community/index/Community.tsx, src/page/community/search/index/Search.tsx, src/page/login/Login.tsx, src/page/main/index/Main.tsx, src/page/mypage/index/Mypage.tsx, src/page/mypage/index/component/MyPageContent/MyPageContent.tsx, src/page/onboarding/complete/Complete.tsx, src/page/onboarding/index/Onboarding.tsx, src/page/onboarding/index/component/nickname/Nickname.tsx, src/page/profile/index/Profile.tsx, src/page/setting/edit-profile/ProfileEdit.tsx, src/page/setting/index/Setting.tsx, src/page/test/Test.tsx, src/route/useProtectedRoute.tsx
=> [Feat/#173] 로컬스토리지 세팅 삭제, 비정상 주소 접근 방지 로직 추가

package.json, pnpm-lock.yaml
- close #239 
의존성 설치하면 다음과 같은 warn 이 뜹니다. 
그냥 경고긴 해서 넘어가려고 하다가, Next.js 작업하면서도 오류 날 것 같아서 먼제 잡고 가려고 합니다.
해결 방법은 다음과 같습니다. 
1. vanilla-extract/vite-plugin을 최신 버전으로 업데이트
`pnpm update @vanilla-extract/vite-plugin`
처음으로 생각한 건, 오류나는 이 플러그인을 업데이트 해보는 것이였는데
하단에 나온 내용과 같이, 오류가 잡히진 않습니다.
2. Vite 버전을 다운그레이드 (Vite 5 사용)
다운그레이드 하고 나서, 다시 의존성 설치 시 아무런 오류 안 잡히는 것을 확인할 수 있었습니다.
vite 라서 사실 다운그레이드 하는 것에.. 괜찮을까 싶은 마음이 있긴 했습니다.
혹시나 다른 의견 주시면 감사합니다 !!
=> [Bug/#239] vite version 오류

src/app/review/complete/page.tsx, src/app/review/complete/style.css.ts
- close #266 
리뷰 등록 완료(review/complete) 뷰 퍼블리싱 완료 했습니다.
확인하기 버튼의 경우 아직 확정받지 못해서 main으로 이동하게 임시 처리해두었고, 
추후 확정나면 `path`활용해서 수정하겠습니다. 
-  확인하기 버튼 사이즈를 고정했습니다!
확인하기 사이즈가 '리뷰가 등록되었어요' 타이틀 `width`사이즈와 동일하길래, 이를 의도하신거 같아 다른 뷰와 달리 width값을 고정했습니다.
https://github.com/user-attachments/assets/eed03ea1-3263-4fe5-8335-d692f1af092d
=> [Feat/#266] 리뷰 등록 완료 뷰 퍼블리싱

src/asset/svg/IcChevronRight.tsx, src/shared/component/LoginPopup/LoginPopup.css.ts, src/shared/component/LoginPopup/LoginPopup.tsx
- close #278 
사용하실 곳 아무곳에나 해당 컴포넌트 써서 사용하시면 됩니다 ~
isOpen으로 보여줄지 여부 결정하시면 되고, onClick으로 클릭시 실행할 함수 연결하면 끝!
```
<LoginPopup
isOpen={true}
onClick={() => {
alert("로그인 후 이용해주세요.");
}}
/>
```
=> [Feat/#278] LoginPopup 컴포넌트 구현

src/api/shared/hook.ts, src/api/shared/index.ts, src/app/layout.tsx, src/app/mypage/_component/ContentSection/ContentSection.tsx, src/app/mypage/_component/HeaderSection/HeaderSection.tsx, src/app/mypage/_component/MyPageContent/MyPageContent.tsx, src/app/mypage/_component/ProfileSection/ProfileSection.tsx, src/app/mypage/_hooks/useMypageState.ts, src/app/mypage/_hooks/useProfileSectionState.ts, src/app/mypage/_store/mypageStore.ts, src/app/mypage/edit-pet/PetEdit.css.ts, src/app/mypage/edit-pet/page.tsx, src/app/mypage/page.tsx, src/app/page.tsx, src/common/component/Button/styles.css.ts, src/providers/AuthProvider.tsx, src/shared/component/HospitalReviewWrapper.tsx, tsconfig.json
사용 방법에 대해 정리해놓아요.
1. 사용하고자 하는 컴포넌트에서 ` const { isAuthenticated } = useAuth();` 와 같은 방식으로 
isAuthenticated를 불러와서 로그인 여부를 결정짓는다.
2. 만약 필요하다면 `const {login, logout} = useAuth();` 를 통해 로그인, 로그아웃 함수를 사용한다. 
아래는 사용 예시에요. (로그인, 로그아웃 판별)
사용방법만 익히면 되는거라, 빠르게 머지할게요!
간단하게 확인후 어프룹 부탁드립니다~!
=> [Feat/Auth Provider] 전역적으로 사용할 AuthProvider 작성

src/app/profile/page.tsx, src/app/setting/page.tsx, src/shared/component/HospitalReviewWrapper.tsx
- close #338 
3가지 페이지의 비로그인 로직을 모두 적용하면서, 작업을 끝냅니다.
전에 useAuth를 만드는 PR에서 마이페이지도 어쩌다보니 조금은 같이 작업이 되어서, 
현재 PR에서는 작업이 그리 많지 않아요.
`const {isAuthenticated} = useAuth();`
만 사용하면 되니까 금방 끝났네요. 다들 잘 이용하셨으면 좋겠어요!
=> [Feat/#338] 비로그인 로직 작성(마이페이지, 프로필페이지 등등)

src/api/shared/hook.ts, src/app/mypage/_component/AddFavoriteHospital.tsx, src/app/mypage/_component/MyPageContent/MyPageContent.tsx, src/app/mypage/_style/mypage.css.ts, src/app/mypage/page.tsx, src/app/onboarding/index/Onboarding.tsx, src/app/profile/_component/ProfileSection/ProfileSection.tsx, src/app/profile/_style/profile.css.ts, src/app/profile/page.tsx, src/auth/RedirectKakao.tsx, src/common/component/Content/Content.tsx, src/route/useProtectedRoute.tsx, src/shared/component/HospitalReviewWrapper.tsx, src/shared/component/SearchHospital/SearchHospital.tsx
- close #382 
단순 QA 목록 뿐만 아니라, 작업 중 발견된 버그들도 같이 수정했어요. 
커밋은 QA 단위로 나눠두어 좀 많아보이지만, 작업양 자체는 그리 많진 않아요. 간단하게만 확인하고 어프룹 부탁드려요~!
참고하시면 좋을 것 같아 간단히 정리해둡니다.
DOM이 수정되면 스크롤 상태를 잃게 돼요.  (예를 들어, DOM 요소의 height가 변하면 DOM이 변하게 돼요.)
페이지네이션시 맨 위로 스크롤 되게 했던 것도, 기존에는 무한 스크롤을 고려하지 않고 height를 auto로 해두었기 때문이에요.
따라서 height를 고정해두고 overflow: scroll로 요소를 다루어 무한스크롤에도 스크롤의 상태를 잃지 않도록 방지했어요.
=> [QA][#382] 마이페이지 / 프로필페이지 / 병원검색필터 QA 반영

src/app/review/complete/page.tsx, src/app/review/write/_component/DirectMyPetInfo.tsx, src/app/review/write/_component/ReviewHospital.tsx, src/app/review/write/_component/ReviewPetInfo.tsx, src/app/review/write/_component/ReviewPurpose.tsx, src/app/review/write/_section/Step1.tsx, src/app/review/write/_section/Step3.tsx, src/app/review/write/_section/Step4.tsx, src/app/review/write/page.tsx, src/common/component/Chip/Chip.tsx, src/common/component/Chip/ChipStyle.css.ts, src/common/component/Radio/Radio.css.ts, src/route/path.ts, src/shared/component/SearchHospital/Card.css.ts, src/shared/component/SearchHospital/Card.tsx
- close #397 
작업 리스트와 커밋 순서가 일치합니다. (마지막 태스크는 커밋3개 쭉 순서대로 보시면 됩니다.)
모든 변경사항은 이미지 또는 영상 첨부했습니다. 첨부하지 않은 것 중 변화는 없습니당.
신경쓴다고 썼는데.. QA가 생각보다 더 많네요.. 앞으로 더 작업에 유의하겠습니다.
- 카드 레이아웃 수정전, 수정후
- 몸무게 반영 확인
- 병원 카드 라디오 컴포넌트 찌그러짐, 찌그러짐 해결
- 칩 분기 추가 반영 (배경 블루, 글자 흰색)
- 진료경험 하나만 선택해도 되도록 수정
https://github.com/user-attachments/assets/a7a26d61-b203-4bfc-9f47-5a9c3de44603
- 업로드 버튼 작동
https://github.com/user-attachments/assets/82cd6624-f155-4c52-aca6-995d8d51f205
- 드롭다운 필터링 잘되게 수정(고양이 -> 고양이 드롭다운/ 강아지 -> 강아지 드롭다운)
https://github.com/user-attachments/assets/938e0e03-e878-4156-add9-f289447b9e80
- 다음으로 버튼 이동 시 정보저장 UI반영 및 활성화 버튼 정상화
https://github.com/user-attachments/assets/ac9a0dc6-2f9a-434f-8ef7-3087600f0b0e
=> [QA/#397]review write qa 

src/app/api/review/agree/hook.ts, src/app/api/review/agree/index.ts, src/app/register-pet/index/RegisterPet.tsx, src/app/register-pet/index/component/petHealth/PetHealth.tsx, src/app/register-pet/index/component/petName/PetName.tsx, src/app/review/agree/page.tsx, src/app/review/page.tsx, src/app/review/write/_section/Step4.tsx
- close #i389
**전체적으로 api 중복 요청을 방지하는 작업을 했습니다.**
1️⃣  반려동물 등록, 리뷰 작성 완료 더블클릭 방지 
: 구현도 하고 검증 콘솔도 작성해 봤는데, 페이지 넘어가기 전에 더블 클릭을 하는게 어렵더라구요,, 별도의 확인 영상은 없습니다..
2️⃣ 리뷰 동의 여부 조회 api 연동
: 죄송합니다.. 리뷰 동의에 대한 개념을 잘못 이해해서 api 하나가 누락되었더라구요.
저는 매 리뷰마다 리뷰 동의를 해야한다고 생각했는데, 회원가입 후 리뷰 동의는 딱 1번만 받는다고 합니다.
따라서 리뷰 동의를 한 적이 있다면 별도의 리뷰 페이지 없이 바로 리뷰 작성으로 넘어가도록 구현했습니다.
3️⃣ url 직접입력시 대응
: 위 두가지 모두 버튼을 클릭해 넘어가는 부분 말고도 url을 직접 입력하고 들어가는 경우도 고려해서 "반려동물 등록", "리뷰 동의 여부조회 페이지"의 경우에는 handle함수 외에도 페이지 로드 시 이미 반려동물이 등록 되어있다면, 리뷰 동의 처리가 되어 있다면 진입하지 못하거나 다음페이지로 넘어가도록 구현해 두었습니다. 
- 반려동물 등록되어 있다면, 반려동물 등록페이지 진입 금지
https://github.com/user-attachments/assets/7c8d7d2a-21dc-422f-8335-6da05ecbfb41
- 리뷰를 동의한 유저가 리뷰 동의페이지
https://github.com/user-attachments/assets/f8807de8-26c6-4f60-987f-bf62232ae0ee
로 강제 진입시 이전으로 이동
- 리뷰를 동의한 유저가 …
=> [QA/#389] api 중복요청 방지작업 (동물등록, 리뷰등록, 리뷰동의)

src/app/onboarding/index/Onboarding.tsx, src/app/review/agree/page.tsx, src/app/review/page.tsx, src/route/useProtectedRoute.tsx
- close #419 
1️⃣ 리뷰 약관에 동의하지 않은 유저임에도 불구하고, 리뷰 작성 페이지로 바로 이동하는 문제가 있었습니다.
리뷰 약관 동의 여부를 판별하는 커스텀 훅을 구현했지만, 응답 데이터의 실제 값을 확인하지 않고 존재 여부만으로 조건 분기를 하여 항상 true로 평가되는 문제가 있었습니다.
응답 객체 내부의 실제 동의 여부(`isReviewTermsAgree`) 값을 기준으로 분기하도록 수정하여 문제를 해결했습니다.
2️⃣ 탈퇴> 회원가입> 닉네임 등록 페이지인 /onboarding로딩 안되는 이슈 발생
참고커밋) "chore: 주석 삭제"
해당 주석이 항상 true로 반환되더라구요, `useProtectedRoute` 로직을 수정했습니다.
수정 포인트는 
> 닉네임이 없는 경우라도,
> 현재 경로가 /onboarding일 때는 리다이렉트하면 안 되는데
> 이전 코드에서는 이 예외 처리가 누락되어 있었기 때문에
> 계속 온보딩 페이지 진입이 막혔던 것입니다.
해서 닉네임 없는 경우 1) 온보딩 페이지인 경우와 2) 온보딩 페이지가 아닌 경우로 나누어 훅을 수정했습니다.
- 리뷰 약관 동의 페이지로 잘 넘어감 확인
https://github.com/user-attachments/assets/afc2dc2b-9742-47f8-83ef-c792816519a2
- 리뷰 약관 동의 펭페이지로 잘 넘어감
https://github.com/user-attachments/assets/84ad087c-8405-4932-a069-e44a93fa829c
=> [Feat/#419] onboarding, review agree qa

src/api/domain/mypage/edit-pet/index.ts, src/app/community/search/done/SearchDone.tsx, src/app/community/search/page.tsx
- close #433
> 필터에서 선택했을 때 폴더?열린 상태도 유지되어야할 거 같아요 
> 선택할 때마다 리로드가 되는 거 같네요
해당 VOC 를 해결합니다. 
선택할 때마다 드롭다운이 닫혀버리고 리로드 되는 문제를 해결했어요. 
유저가 클릭할 때는 그냥 select 만 하고, 확인하기 누를 때에만 api 를 호출하도록 했습니다. 
[ AS-IS ] 
https://github.com/user-attachments/assets/98f1c7f5-233a-437e-acb5-79773d9b6d74
[ TO-BE ] 
https://github.com/user-attachments/assets/e2e87374-4832-494d-9bb5-c65838646355
=> [Bug/#433] 검색 창 필터 바텀 시트의 reload 문제 해결

pages/_document.tsx, src/app/layout.tsx, src/common/component/TextField/index.tsx, src/common/component/TextField/styles.css.ts
- close #471
유저가 작성할 때 input 에서 확대가 되지 않도록 수정했어요. 
컴퓨터로는 재현이 불가능하고 핸드폰으로만 확인이 가능해서 영상 첨부합니다. 
[as-is]
https://github.com/user-attachments/assets/15cf1060-b4d3-403b-b1ce-3853c0f3cd7e
[to-be] 
https://github.com/user-attachments/assets/8f07fb06-6505-420f-bd86-ba8ed6aeabeb
피그마 에 있는 것을 기반으로 똑같이 반영되도록 수정했어요. 
높이와 padding 위주로 수정되었습니다. 
X 버튼이 묘하게 위로 치우진다는 QA 를 커버하기 위해 center 정렬도 해두었어요.
=> [Feat/#471] scale 조정 안되도록 수정, Input 수정
